config/routes.rb
Rails.application.routes.draw do

  # ===========================
  # 	    ROOT DEFINITION
  # ===========================
  root to: 'home#index'

  devise_for :users
  apipie

  # ===========================
  #      DASHBOARDS ROUTES
  # ===========================
  get 'torcida_dash' => 'home#torcida_dash', as: :torcida_dash
  get 'time_dash' => 'home#time_dash', as: :time_dash

  # ===========================
  #        CLUBES ROUTES
  # ===========================
  get 'clubes/new_manager'
  get 'clubes/edit_manager/:id' => 'clubes#edit_manager', as: :edit_clube_admin
  delete 'clubes/destroy_manager/:id' => 'clubes#destroy_manager', as: :destroy_clube_manager
  post 'create_clubes_manager' => 'clubes#create_manager', as: :create_clubes_manager
  post 'edit_clubes_manager' => 'clubes#edit_clubes_manager', as: :edit_clubes_manager
  get 'clube_active/:id' => 'clubes#active', as: :clube_active
  get 'clube_desactive/:id' => 'clubes#desactive', as: :clube_desactive
  get 'clube_admins' => 'clubes#admins', as: :clube_admins

  # ===========================
  #        TORCIDAS ROUTES
  # ===========================
  get 'torcidas/new_manager'
  get 'torcidas/edit_manager/:id' => 'torcidas#edit_manager', as: :edit_torcida_admin
  delete 'torcidas/destroy_manager/:id' => 'torcidas#destroy_manager', as: :destroy_torcida_manager
  post 'create_torcida_manager' => 'torcidas#create_manager', as: :create_torcida_manager
  post 'edit_torcida_manager' => 'torcidas#edit_torcida_manager', as: :edit_torcida_manager
  get 'torcida_active/:id' => 'torcidas#active', as: :torcida_active
  get 'torcida_desactive/:id' => 'torcidas#desactive', as: :torcida_desactive
  get 'torcida_admins' => 'torcidas#admins', as: :torcida_admins

  # ===========================
  #        USERS ROUTES
  # ===========================
  get 'approve_user/:id' => 'user#approve', as: :approve_user

  # ===========================
  #         RESOURCES
  # ===========================
  resources :users
  resources :clubes
  resources :torcidas
  resources :questions
  
  # ===========================
  # 	      WEBSERVICES
  # ===========================
  namespace :webservices do
  	# ===========================
  	# 	     LOGIN METHODS 
  	# ===========================
  	post '/login/signin'
  	post '/login/signup'
  	post '/login/update_photos'
  	post '/login/update_question'
    post '/login/update_address'
    post '/login/complete_login'
    post '/login/set_payment'
    
    # ===========================
    #       ACCOUNT METHODS 
    # ===========================
    get  '/account/getAbout'

	  # ===========================
  	# 	   QUESTION METHODS 
  	# ===========================
  	get  '/questions/getQuestion'
    post '/questions/checkQuestion'
    
    # ===========================
    #        TIME METHODS
    # ===========================
    get  '/times/getTimes'

    # ===========================
    #      TORCIDAS METHODS 
    # ===========================
    get  '/torcidas/getTorcidas'
  end

end

app/models/torcida.rb
class Torcida
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :name, type: String
  field :picture_file_name, type: String
  field :picture_file_size, type: String
  field :picture_content_type, type: String
  field :active, type: Integer, default: 1

  belongs_to :clube
  has_many :users
  
  has_mongoid_attached_file :picture, 
    :styles => { :medium => "320x320>", :thumb => "160x160#" },
    :storage        => :s3,
    :bucket_name    => 'TorcidaLegal',
    :bucket    => 'TorcidaLegal',
    :path           => ':attachment/:id/:style.:extension',
    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')
  validates_attachment_size :picture, :less_than => 5.megabytes
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/jpg']

  def self.mapTorcida(c)
    arr = []
    c.each do |cu|
      arr <<  { :id => cu.id.to_s, :name => cu.name, :picture => cu.picture }
    end
    arr
  end

end

app/controllers/torcidas_controller.rb
class TorcidasController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  # =================================
  #      INDEX TORCIDAS METHOD
  # =================================
  def index
    @torcidas = Torcida.all
  end
  
  # =================================
  #        TORCIDA NEW METHOD
  # =================================
  def new
    @torcida = Torcida.new
    @clubes = Clube.all
  end

  # =================================
  #       EDIT TORCIDA METHOD
  # =================================
  def edit
    @torcida = Torcida.find(params[:id])
    @clubes = Clube.all
  end

  # =================================
  #        SHOW TORCIDA METHOD
  # =================================
  def show
  end

  # =================================
  #        SHOW ADMINS METHOD
  # =================================
  def admins
    @users = User.where(:user_type => 'torcidaUser')
  end
  
  # =================================
  #      ACTIVATE TORCIDA METHOD
  # =================================
  def active
    @torcida = Torcida.find(params[:id])

    if @torcida.clube.active > 0
      if @torcida.update(:active => 1)
        redirect_to torcidas_path, notice: 'Torcida ativada com sucesso'
      else
        redirect_to torcidas_path, alert: 'Não foi possivel ativar o torcida, tente novamente mais tarde'
      end
    else
      redirect_to torcidas_path, alert: 'Time inteiro está desativado, para completar essa ação ative o time primeiro!'
    end
  end
  
  # =================================
  #     DESACTIVATE TORCIDA METHOD
  # =================================
  def desactive
    @torcida = Torcida.find(params[:id])
    if @torcida.update(:active => 0)
      redirect_to torcidas_path, notice: 'Torcida desativada com sucesso'
    else
      redirect_to torcidas_path, alert: 'Não foi possivel desativar a torcida, tente novamente mais tarde'
    end
  end

  # =================================
  #      NEW MANAGER VIEW METHOD
  # =================================
  def new_manager
    @torcidas = Torcida.all
  end

  # =================================
  #      CREATE MANAGER METHOD
  # =================================
  def create_manager
    @def = User.new(manager_params)

    if @def.save(validate: false)
      redirect_to torcida_admins_path, notice: 'Administrador criado com sucesso'
    else
      redirect_to torcida_admins_path, alert: 'Erro ao criar administrador'
    end

  end

  # =================================
  #       CREATE TORCIDA METHOD
  # =================================
  def create
    @torcida = Torcida.new(torcida_params)

    if @torcida.save
      redirect_to edit_torcida_path(@torcida.id)
    else
      render 'new'
    end
  end

  # =================================
  #      EDIT MANAGER VIEW METHOD
  # =================================
  def edit_manager
    @torcidas = Torcida.all
    @manager = User.find(params[:id])
  end

  # =================================
  #      DESTROY MANAGER METHOD
  # =================================
  def destroy_manager
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to torcida_admins_path, notice: 'Administrador deletado com sucesso'
    else
      redirect_to torcida_admins_path, alert: 'Não foi possivel deletar o administrador'
    end
  end

  # =================================
  #       EDIT TORCIDA METHOD
  # =================================
  def edit_torcida_manager
    @def = User.find(params[:manager][:id])

    params[:manager][:name].blank? ? '' : @def.name = params[:manager][:name]
    params[:manager][:email].blank? ? '' : @def.email = params[:manager][:email]
    params[:manager][:cpf].blank? ? '' : @def.cpf = params[:manager][:cpf]
    params[:manager][:password].blank? ?  '' : @def.password = params[:manager][:password]
    params[:manager][:password_confirmation].blank? ? ''  : @def.password_confirmation = params[:manager][:password_confirmation]
    params[:manager][:torcida_id].blank? ? '' : @def.torcida_id = params[:manager][:torcida_id]

    if @def.save(validate: false)
      redirect_to torcida_admins_path, notice: 'Administrador editado com sucesso'
    else
      redirect_to torcida_admins_path, alert: 'Erro ao criar administrador'
    end
  end

  # =================================
  #      UPDATE TORCIDA METHOD
  # =================================
  def update
    @torcida = Torcida.find(params[:id])

    if @torcida.update(torcida_params)
      redirect_to edit_torcida_path(@torcida.id)
    else
      render 'new'
    end
  end

  # =================================
  #      DESTROY TORCIDA METHOD
  # =================================
  def destroy
    @torcida = Torcida.find(params[:id])

    if @torcida.destroy
      redirect_to torcidas_path
    else
      redirect_to torcidas_path
    end
  end

  private
    def torcida_params
      params.require(:torcida).permit(:name,:picture,:clube_id)
    end

    def manager_params
      params.require(:manager).permit(:name,:email,:cpf,:password,:password_confirmation,:torcida_id,:user_type)
    end
end

app/controllers/webservices/torcidas_controller.rb
class Webservices::TorcidasController < WebservicesController
	# =============================================================
	# 					    GET TORCIDas METHOD
	# =============================================================
	api :GET, '/torcidas/getTorcidas', "Get all"
	formats ['json']
	param :id, String, :desc => 'ID do time', :required => true, :missing_message => lambda { "ID do time é requerido" }
	error 402, "Nenhum time encontrado"
	error 500, "Erro desconhecido"
	example "Exemplo de retorno
	
	{ 
		:message => 'Times carregados com sucesso',
		:torcidas => [
			{ :id => '12381763782618s78', :name => 'Time tal', :picture => 'http://s3.amazonaws.com/TorcidaLegal/pictures/59484ad9a3f9f30004362d6b/original.png?1497909989' },
			{ :id => '12381763782618s78', :name => 'Time tal', :picture => 'http://s3.amazonaws.com/TorcidaLegal/pictures/59484ad9a3f9f30004362d6b/original.png?1497909989' }
		]
	}"
	example "Exemplo de retorno quando não estiver feito login

	{ 
		:message => 'Faça o login para continuar',
	}"
	example "Exemplo de retorno quando não forem encontradas perguntas

	{ 	
		:message => 'Nenhuma torcida encontrada',
	}"
	def getTorcidas
		t = Torcida.where(:clube_id => params[:id], :active => 1)
		
		if t.blank?
			render :json => { :message => 'Nenhuma torcida encontrada' }, :status => 402
		else
			render :json => { :message => 'Torcidas carregadas com sucesso', :torcidas => Torcida.mapTorcida(t) }
		end
	end
end

app/helpers/torcidas_helper.rb
module TorcidasHelper
end

app/helpers/webservices/torcidas_helper.rb
module Webservices::TorcidasHelper
end

app/views/torcidas/_form.html.erb
<%= form_for @torcida do |f| %>
	<%= f.label :nome %>
	<%= f.text_field :name, :class => 'form-control', :placeholder => 'Nome da Torcida' %><br>
	<%= f.label :logo %>
	<%= f.file_field :picture, :class => 'form-control', :placeholder => 'Logo' %><br>
	<%= f.label :time %>
	<%= f.select(:clube_id, {},{},{:class => 'form-control'}) do %>
		<% @clubes.each do |c| %>
			<%= content_tag(:option, c.name, value: c.id) %>
		<% end %>
	<% end %><br>
	<%= f.submit({:class => 'btn btn-success'}) %>
<% end %>

app/views/torcidas/admins.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'home/sidebar' %>
        
        <%= render 'home/topbar' %>

        <!-- page content -->
        <div class="right_col" role="main">
          
          <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Administradores de Torcidas</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Nome</th>
                          <th>Email</th>
                          <th>Torcida</th>
                          <th style="width:80px">Opções</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @users.each do |u| %>
                        <tr>
                          <td><%= u.name %></td>
                          <td><%= u.email %></td>
                          <td><%= u.torcida.name %></td>
                          <td>
                              <div class="btn-group">
                              <button type="button" class="btn btn-default">Opções</button>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="<%= edit_torcida_admin_path(u.id) %>"><i class="fa fa-pencil"></i> Editar Admin</a></li>
                                  <li><a href="<%= destroy_torcida_manager_path(u.id) %>" data-confirm="Tem certeza que deseja deletar o Administrador <%= u.name %>? " data-method="delete" rel="nofollow"><i class="fa fa-trash"></i> Deletar Admin</a></li>
                              </ul>
                          </div>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

   <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>
  
    <% if flash[:notice] %>
      <script type="text/javascript">
        swal('Okay', '<%= flash[:notice] %>', 'success');
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
        swal('Ops', '<%= flash[:alert] %>', 'warning');
      </script>
    <% end %>

  </body>
</html>

app/views/torcidas/create.html.erb
<h1>Torcidas#create</h1>
<p>Find me in app/views/torcidas/create.html.erb</p>

app/views/torcidas/destroy.html.erb
<h1>Torcidas#destroy</h1>
<p>Find me in app/views/torcidas/destroy.html.erb</p>

app/views/torcidas/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'home/sidebar' %>
        
        <%= render 'home/topbar' %>

        <!-- page content -->
        <div class="right_col" role="main">
          
          <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Torcidas</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Nome</th>
                          <th>Time</th>
                          <th>Thumb</th>
                          <th>Status</th>
                          <th style="width:80px">Opções</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @torcidas.each do |u| %>
                        <tr>
                          <td><%= u.name %></td>
                          <td><%= u.clube.name %></td>
                          <td><%= image_tag(u.picture.url(:thumb)) %></td>
                          <td>
                            <% if u.active > 0 %>
                              <div class="label label-success">Ativo</div>
                            <% else %>
                              <div class="label label-danger">Inativo</div>
                            <% end %>
                          </td>
                          <td>
                              <div class="btn-group">
                              <button type="button" class="btn btn-default">Opções</button>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="<%= edit_torcida_path(u.id) %>"><i class="fa fa-pencil"></i> Editar Torcida</a></li>
                                  <li><a href="<%= torcida_path(u.id) %>" data-confirm="Tem certeza que deseja deletar a Torcida <%= u.name %>?" data-method="delete" rel="nofollow"><i class="fa fa-trash"></i> Deletar Time</a></li>
                                  <% if u.active > 0 %>
                                    <li><a href="<%= torcida_desactive_path(u.id) %>"><i class="fa fa-close"></i> Desativar</a></li>
                                  <% else %>
                                    <li><a href="<%= torcida_active_path(u.id) %>"><i class="fa fa-check"></i> Ativar</a></li>
                                  <% end %>
                              </ul>
                          </div>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

   <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>

    <% if flash[:notice] %>
      <script type="text/javascript">
        swal('Okay', '<%= flash[:notice] %>', 'success');
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
        swal('Ops', '<%= flash[:alert] %>', 'warning');
      </script>
    <% end %>
  
  </body>
</html>

app/views/torcidas/show.html.erb
<h1>Torcidas#show</h1>
<p>Find me in app/views/torcidas/show.html.erb</p>

app/views/torcidas/update.html.erb
<h1>Torcidas#update</h1>
<p>Find me in app/views/torcidas/update.html.erb</p>