config/routes.rb
Rails.application.routes.draw do

  # ===========================
  # 	    ROOT DEFINITION
  # ===========================
  root to: 'home#index'

  devise_for :users
  apipie

  # ===========================
  #      DASHBOARDS ROUTES
  # ===========================
  get 'torcida_dash' => 'home#torcida_dash', as: :torcida_dash
  get 'time_dash' => 'home#time_dash', as: :time_dash

  # ===========================
  #        CLUBES ROUTES
  # ===========================
  get 'clubes/new_manager'
  get 'clubes/edit_manager/:id' => 'clubes#edit_manager', as: :edit_clube_admin
  delete 'clubes/destroy_manager/:id' => 'clubes#destroy_manager', as: :destroy_clube_manager
  post 'create_clubes_manager' => 'clubes#create_manager', as: :create_clubes_manager
  post 'edit_clubes_manager' => 'clubes#edit_clubes_manager', as: :edit_clubes_manager
  get 'clube_active/:id' => 'clubes#active', as: :clube_active
  get 'clube_desactive/:id' => 'clubes#desactive', as: :clube_desactive
  get 'clube_admins' => 'clubes#admins', as: :clube_admins

  # ===========================
  #        TORCIDAS ROUTES
  # ===========================
  get 'torcidas/new_manager'
  get 'torcidas/edit_manager/:id' => 'torcidas#edit_manager', as: :edit_torcida_admin
  delete 'torcidas/destroy_manager/:id' => 'torcidas#destroy_manager', as: :destroy_torcida_manager
  post 'create_torcida_manager' => 'torcidas#create_manager', as: :create_torcida_manager
  post 'edit_torcida_manager' => 'torcidas#edit_torcida_manager', as: :edit_torcida_manager
  get 'torcida_active/:id' => 'torcidas#active', as: :torcida_active
  get 'torcida_desactive/:id' => 'torcidas#desactive', as: :torcida_desactive
  get 'torcida_admins' => 'torcidas#admins', as: :torcida_admins

  # ===========================
  #        USERS ROUTES
  # ===========================
  get 'approve_user/:id' => 'user#approve', as: :approve_user

  # ===========================
  #         RESOURCES
  # ===========================
  resources :users
  resources :clubes
  resources :torcidas
  resources :questions
  
  # ===========================
  # 	      WEBSERVICES
  # ===========================
  namespace :webservices do
  	# ===========================
  	# 	     LOGIN METHODS 
  	# ===========================
  	post '/login/signin'
  	post '/login/signup'
  	post '/login/update_photos'
  	post '/login/update_question'
    post '/login/update_address'
    post '/login/complete_login'
    post '/login/set_payment'
    
    # ===========================
    #       ACCOUNT METHODS 
    # ===========================
    get  '/account/getAbout'

	  # ===========================
  	# 	   QUESTION METHODS 
  	# ===========================
  	get  '/questions/getQuestion'
    post '/questions/checkQuestion'
    
    # ===========================
    #        TIME METHODS
    # ===========================
    get  '/times/getTimes'

    # ===========================
    #      TORCIDAS METHODS 
    # ===========================
    get  '/torcidas/getTorcidas'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	before_action :check_admin

	# =================================
	# 		  DASHBOARD METHOD
	# =================================
	def index
		@users = User.where(:user_type => 'User')
		@questions = Question.all
		@clubes = Clube.all
		@torcidas = Torcida.all
		@backlog = Backlog.all.order(created_at: :desc)
		@page = 'Home'
	end
	
	# =================================
	# 	   TORCIDA DASHBOARD METHOD
	# =================================
	def torcida_dash
		@users = User.where(:user_type => 'User',:torcida_id => current_user.torcida_id)
		@page = 'Home'
	end
	
	# =================================
	# 	    TIME DASHBOARD METHOD
	# =================================
	def time_dash
		@users = User.where(:user_type => 'User')
		@questions = Question.all
		@clubes = Clube.all
		@torcidas = Torcida.all
		@backlog = Backlog.all.order(created_at: :desc)
		@page = 'Home'
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidebar.html.erb
<div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="#" class="site_title"><i class="fa fa-users"></i> <span>Torcida Legal</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info --> 
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="/production/images/logo.png" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Bem-vindo,</span>
                <h2><%= current_user.name %></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->
            
            <br />
            
            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li <% if @page == 'Home' %> class="active" <% end %> ><a href="<%= root_path %>"><i class="fa fa-home"></i> Home</a>
                  </li>
                  <% if current_user.user_type == 'superUser' %>
                  <li><a href="<%= users_path %>"><i class="fa fa-user"></i> Usuários</a>
                  </li>
                  <li><a href="#"><i class="fa fa-table"></i> Perguntas <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="<%= questions_path %>">Ver Perguntas</a></li>
                    </ul>
                  </li>
                  <li><a href="#"><i class="fa fa-table"></i> Times <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/clubes/new_manager">Novo Admin</a></li>
                      <li><a href="<%= clube_admins_path %>">Ver Admin</a></li>
                      <li><a href="<%= new_clube_path %>">Novo Time</a></li>
                      <li><a href="<%= clubes_path %>">Ver Times</a></li>
                    </ul>
                  </li>
                  <li><a href="#"><i class="fa fa-users"></i> Torcidas <span class="fa fa-chevron-down"></span></a> 
                    <ul class="nav child_menu">
                      <li><a href="/torcidas/new_manager">Novo Admin</a></li>
                      <li><a href="<%= torcida_admins_path %>">Ver Admin</a></li>
                      <li><a href="<%= new_torcida_path %>">Nova Torcida</a></li>
                      <li><a href="<%= torcidas_path %>">Ver Torcidas</a></li>
                    </ul>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="/users/sign_out" data-method="delete">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

app/views/home/_topbar.html.erb
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="/production/images/logo.png" alt=""><%= current_user.name %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="/users/sign_out" data-method="delete"><i class="fa fa-sign-out pull-right"></i> Sair</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>


    <title>Torcida Legal</title>
    
    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    
    <!-- bootstrap-progressbar -->
    <link href="../vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="../vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="../vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">

        <%= render 'sidebar' %>

        <%= render 'topbar' %>
        
        <!-- page content -->
        <div class="right_col" role="main">
          <!-- top tiles -->
          <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Usuários do App</span>
              <div class="count"><%= @users.count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-table"></i> Perguntas Cadastradas</span>
              <div class="count"><%= @questions.count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-table"></i> Clubes</span>
              <div class="count"><%= @clubes.count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-table"></i> Torcidas</span>
              <div class="count"><%= @torcidas.count %></div>
            </div>
          </div>
          <!-- /top tiles -->

          <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Atividades Recentes <small>Geral</small></h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <div class="dashboard-widget-content">

                    <ul class="list-unstyled timeline widget">
                    
                      <% @backlog.take(10).each do |b| %>
                      <li>
                        <div class="block">
                          <div class="block_content">
                            <h2 class="title">
                                              <a><%= b.description %></a>
                                          </h2>
                            <div class="byline">
                              <span><%= b.created_at.strftime('%d/%m/%y %H:%M') %></span></a>
                            </div>
                          </div>
                        </div>
                      </li>
                      <% end %>
                      
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-8 col-sm-8 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                <h4>Ultimos Usuários Cadastrados</h4>
                </div>
                <div class="x_content">
                  <div class="row">
                    <% @users.order(created_at: :desc).take(4).each do |u| %>
                      <div class="col-md-6 col-sm-6 col-xs-12 profile_details">
                        <div class="well profile_view">
                          <div class="col-sm-12">
                            <h4 class="brief"><i><%= u.occupation %></i></h4>
                            <div class="left col-xs-7">
                              <h2><%= u.name %></h2>
                              <ul class="list-unstyled">
                                <li><i class="fa fa-building"></i> Filiação: <%= u.membership %> </li>
                                <li><i class="fa fa-file-text-o"></i> CPF: <%= u.cpf %> </li>
                                <li><i class="fa fa-hourglass"></i> Status Cadastro: <% if u.status == 1 %>20%<% elsif u.status == 2 %>40%<% elsif u.status == 3 %>60%<% elsif u.status == 4 %>80%<% elsif u.status == 5 %>90%<% elsif u.status == 6 %>OK<% end %> </li>
                              </ul>
                            </div>
                            <div class="right col-xs-5 text-center">
                              <img src="<%= u.picture.url(:thumb) %>" alt="" class="img-circle img-responsive">
                            </div>
                          </div>
                          <div class="col-xs-12 bottom text-center">
                            <div class="col-xs-12 text-right col-sm-6 col-sm-offset-6 emphasis">
                              <a href="<%= user_path(u.id) %>" type="button" class="btn btn-primary btn-xs">
                                <i class="fa fa-user"> </i> Visualizar
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="../vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="../vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="../vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="../vendors/Flot/jquery.flot.js"></script>
    <script src="../vendors/Flot/jquery.flot.pie.js"></script>
    <script src="../vendors/Flot/jquery.flot.time.js"></script>
    <script src="../vendors/Flot/jquery.flot.stack.js"></script>
    <script src="../vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="../vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="../vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="../vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="../vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="../vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="../vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="../vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="../vendors/moment/min/moment.min.js"></script>
    <script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>
    
    <% if flash[:notice] %>
      <script type="text/javascript">
        swal('Okay', '<%= flash[:notice] %>', 'success');
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
        swal('Ops', '<%= flash[:alert] %>', 'warning');
      </script>
    <% end %>

  </body>
</html>

app/views/home/torcida_dash.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    
    <!-- bootstrap-progressbar -->
    <link href="../vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="../vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="../vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'sidebar' %>

        <%= render 'topbar' %>
        
        <!-- page content -->
        <div class="right_col" role="main">
          <div class="row">
            <div class="col-md-6">
              <h1><%= current_user.torcida.name %></h1>
            </div>
          </div>
          <!-- top tiles -->
          <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total de Usuários</span>
              <div class="count"><%= @users.count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-check"></i> Usuários Aprovados</span>
              <div class="count"><%= @users.where(:approved_torcida => true).count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-clock-o"></i> Aprovação Pendente</span>
              <div class="count"><%= @users.where(:approved_torcida => false).count %></div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-close"></i> Cadastro Incompleto</span>
              <div class="count">0</div>
            </div>
          </div>
          <!-- /top tiles -->

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h4>Ultimos Usuários Cadastrados</h4>
                </div>
                <div class="x_content">
                  <div class="row">
                    <% @users.order(created_at: :desc).take(4).each do |u| %>
                      <div class="col-md-4 col-sm-4 col-xs-12 profile_details">
                        <div class="well profile_view">
                          <div class="col-sm-12">
                            <h4 class="brief"><i><%= u.occupation %></i></h4>
                            <div class="left col-xs-7">
                              <h2><%= u.name %></h2>
                              <ul class="list-unstyled">
                                <li><i class="fa fa-building"></i> Filiação: <%= u.membership %> </li>
                                <li><i class="fa fa-file-text-o"></i> CPF: <%= u.cpf %> </li>
                                <li><i class="fa fa-hourglass"></i> Status Cadastro: <% if u.status == 1 %>20%<% elsif u.status == 2 %>40%<% elsif u.status == 3 %>60%<% elsif u.status == 4 %>80%<% elsif u.status == 5 %>90%<% elsif u.status == 6 %>OK<% end %> </li>
                              </ul>
                            </div>
                            <div class="right col-xs-5 text-center">
                              <img src="<%= u.picture.url(:thumb) %>" alt="" class="img-circle img-responsive">
                            </div>
                          </div>
                          <div class="col-xs-12 bottom text-center">
                            <% if u.status == 6 %>
                            <div class="col-xs-12 text-left col-sm-6 emphasis">
                              <a href="<%= approve_user_path(u.id) %>" type="button" class="btn btn-success btn-xs">
                                <i class="fa fa-user"> </i> Aprovar
                              </a>
                            </div>
                            <% end %>
                            <div class="col-xs-12 text-right col-sm-6 <% if u.status != 6 %> col-sm-offset-6 <% end %> emphasis">
                              <a href="<%= user_path(u.id) %>" type="button" class="btn btn-primary btn-xs">
                                <i class="fa fa-user"> </i> Visualizar
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="../vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="../vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="../vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="../vendors/Flot/jquery.flot.js"></script>
    <script src="../vendors/Flot/jquery.flot.pie.js"></script>
    <script src="../vendors/Flot/jquery.flot.time.js"></script>
    <script src="../vendors/Flot/jquery.flot.stack.js"></script>
    <script src="../vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="../vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="../vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="../vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="../vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="../vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="../vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="../vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="../vendors/moment/min/moment.min.js"></script>
    <script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>
  
  </body>
</html>