config/routes.rb
Rails.application.routes.draw do

  # ===========================
  # 	    ROOT DEFINITION
  # ===========================
  root to: 'home#index'

  devise_for :users
  apipie

  # ===========================
  #      DASHBOARDS ROUTES
  # ===========================
  get 'torcida_dash' => 'home#torcida_dash', as: :torcida_dash
  get 'time_dash' => 'home#time_dash', as: :time_dash

  # ===========================
  #        CLUBES ROUTES
  # ===========================
  get 'clubes/new_manager'
  get 'clubes/edit_manager/:id' => 'clubes#edit_manager', as: :edit_clube_admin
  delete 'clubes/destroy_manager/:id' => 'clubes#destroy_manager', as: :destroy_clube_manager
  post 'create_clubes_manager' => 'clubes#create_manager', as: :create_clubes_manager
  post 'edit_clubes_manager' => 'clubes#edit_clubes_manager', as: :edit_clubes_manager
  get 'clube_active/:id' => 'clubes#active', as: :clube_active
  get 'clube_desactive/:id' => 'clubes#desactive', as: :clube_desactive
  get 'clube_admins' => 'clubes#admins', as: :clube_admins

  # ===========================
  #        TORCIDAS ROUTES
  # ===========================
  get 'torcidas/new_manager'
  get 'torcidas/edit_manager/:id' => 'torcidas#edit_manager', as: :edit_torcida_admin
  delete 'torcidas/destroy_manager/:id' => 'torcidas#destroy_manager', as: :destroy_torcida_manager
  post 'create_torcida_manager' => 'torcidas#create_manager', as: :create_torcida_manager
  post 'edit_torcida_manager' => 'torcidas#edit_torcida_manager', as: :edit_torcida_manager
  get 'torcida_active/:id' => 'torcidas#active', as: :torcida_active
  get 'torcida_desactive/:id' => 'torcidas#desactive', as: :torcida_desactive
  get 'torcida_admins' => 'torcidas#admins', as: :torcida_admins

  # ===========================
  #        USERS ROUTES
  # ===========================
  get 'approve_user/:id' => 'user#approve', as: :approve_user

  # ===========================
  #         RESOURCES
  # ===========================
  resources :users
  resources :clubes
  resources :torcidas
  resources :questions
  
  # ===========================
  # 	      WEBSERVICES
  # ===========================
  namespace :webservices do
  	# ===========================
  	# 	     LOGIN METHODS 
  	# ===========================
  	post '/login/signin'
  	post '/login/signup'
  	post '/login/update_photos'
  	post '/login/update_question'
    post '/login/update_address'
    post '/login/complete_login'
    post '/login/set_payment'
    
    # ===========================
    #       ACCOUNT METHODS 
    # ===========================
    get  '/account/getAbout'

	  # ===========================
  	# 	   QUESTION METHODS 
  	# ===========================
  	get  '/questions/getQuestion'
    post '/questions/checkQuestion'
    
    # ===========================
    #        TIME METHODS
    # ===========================
    get  '/times/getTimes'

    # ===========================
    #      TORCIDAS METHODS 
    # ===========================
    get  '/torcidas/getTorcidas'
  end

end

app/models/clube.rb
class Clube
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :name, type: String
  field :picture_file_name, type: String
  field :picture_file_size, type: String
  field :picture_content_type, type: String
  field :active, type: Integer, default: 1
  
  has_many :torcidas, dependent: :destroy

  has_mongoid_attached_file :picture, 
    :styles => { :medium => "320x320>", :thumb => "160x160#" },
    :storage        => :s3,
    :bucket_name    => 'TorcidaLegal',
    :bucket    => 'TorcidaLegal',
    :path           => ':attachment/:id/:style.:extension',
    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')
  validates_attachment_size :picture, :less_than => 5.megabytes
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
  
  def self.mapClube(c)
    arr = []
    c.each do |cu|
      arr <<  { :id => cu.id.to_s, :name => cu.name, :picture => cu.picture }
    end
    arr
  end
end

app/controllers/clubes_controller.rb
class ClubesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  # ==============================
  #             INDEX
  # ==============================
  def index
    @clubes = Clube.all
  end
  
  # ==============================
  #               NEW
  # ==============================
  def new
    @clube = Clube.new
  end

  # ==============================
  #             EDIT
  # ==============================
  def edit
    @clube = Clube.find(params[:id])
  end

  # ==============================
  #             SHOW
  # ==============================
  def show
    @clube = Clube.find(params[:id]) rescue nil
  end

  # ==============================
  #             ADMINS
  # ==============================
  def admins
    @users = User.where(:user_type => 'clubeUser')
  end

  # ==============================
  #            ACTIVE
  # ==============================
  def active
    @clube = Clube.find(params[:id])
    if @clube.update(:active => 1)
      @clube.torcidas.each do |t|
        t.update(:active => 1)
      end
      redirect_to clubes_path, notice: 'Clube ativado com sucesso'
    else
      redirect_to clubes_path, alert: 'Não foi possivel ativar o clube, tente novamente mais tarde'
    end
  end
  
  # ==============================
  #           DESACTIVE
  # ==============================
  def desactive
    @clube = Clube.find(params[:id])
    if @clube.update(:active => 0)
      @clube.torcidas.each do |t|
        t.update(:active => 0)
      end
      redirect_to clubes_path, notice: 'Clube desativado com sucesso'
    else
      redirect_to clubes_path, alert: 'Não foi possivel desativar o clube, tente novamente mais tarde'
    end
  end

  # ==============================
  #         NEW MANAGER
  # ==============================
  def new_manager
    @clubes = Clube.all
  end

  # ==============================
  #         CREATE MANAGER
  # ==============================
  def create_manager

    @def = User.new(manager_params)

    if @def.save(validate: false)
      redirect_to clube_admins_path, notice: 'Administrador criado com sucesso'
    else
      redirect_to clube_admins_path, alert: 'Erro ao criar administrador'
    end
    
  end

  # ==============================
  #       EDIT CLUBES MANAGER
  # ==============================
  def edit_clubes_manager
    @def = User.find(params[:manager][:id])

    params[:manager][:name].blank? ? '' : @def.name = params[:manager][:name]
    params[:manager][:email].blank? ? '' : @def.email = params[:manager][:email]
    params[:manager][:cpf].blank? ? '' : @def.cpf = params[:manager][:cpf]
    params[:manager][:password].blank? ?  '' : @def.password = params[:manager][:password]
    params[:manager][:password_confirmation].blank? ? ''  : @def.password_confirmation = params[:manager][:password_confirmation]
    params[:manager][:torcida_id].blank? ? '' : @def.torcida_id = params[:manager][:torcida_id]

    if @def.save(validate: false)
      redirect_to clube_admins_path, notice: 'Administrador editado com sucesso'
    else
      redirect_to clube_admins_path, alert: 'Erro ao criar administrador'
    end
  end

  # ==============================
  #           EDIT MANAGER
  # ==============================
  def edit_manager
    @clubes = Clube.all
    @manager = User.find(params[:id])
  end

  # ==============================
  #       DESTROY MANAGER
  # ==============================
  def destroy_manager
    @manager = User.find(params[:id])

    @manager.destroy

    redirect_to clube_admins_path
  end

  # ==============================
  #             CREATE
  # ==============================
  def create
    @clube = Clube.new(clube_params)

    if @clube.save
      redirect_to edit_clube_path(@clube.id)
    else
      render 'new'
    end
  end

  # ==============================
  #             UPDATE
  # ==============================
  def update
    @clube = Clube.find(params[:id])

    if @clube.update(clube_params)
      redirect_to edit_clube_path(@clube.id)
    else
      render 'edit'
    end
  end

  # ==============================
  #             DESTROY
  # ==============================
  def destroy
    @clube = Clube.find(params[:id]) rescue nil

    if @clube.nil?
      redirect_to clubes_path
    else
      @clube.destroy
      redirect_to clubes_path
    end
  end

  # ==============================
  #             PRIVATE
  # ==============================
  private
    def clube_params
      params.require(:clube).permit(:name,:picture)
    end
    
    def manager_params
      params.require(:manager).permit(:name,:email,:cpf,:password,:password_confirmation,:torcida_id,:user_type)
    end
end

app/helpers/clubes_helper.rb
module ClubesHelper
end

app/views/clubes/_form.html.erb
<%= form_for @clube do |f| %>
	<%= f.label :nome %>
	<%= f.text_field :name, :class => "form-control", :placeholder => 'Nome do Time' %><br>
	<%= f.label :logo %>
	<%= f.file_field :picture, :class => "form-control" %><br>
	<%= f.submit({:class => 'btn btn-success'}) %>
<% end %>

app/views/clubes/admins.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'home/sidebar' %>
        
        <%= render 'home/topbar' %>

        <!-- page content -->
        <div class="right_col" role="main">
          
          <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Administradores de Times</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Nome</th>
                          <th>Email</th>
                          <th>Time</th>
                          <th style="width:80px">Opções</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @users.each do |u| %>
                        <tr>
                          <td><%= u.name %></td>
                          <td><%= u.email %></td>
                          <td><%= u.torcida.clube.name %></td>
                          <td>
                              <div class="btn-group">
                              <button type="button" class="btn btn-default">Opções</button>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="<%= edit_clube_admin_path(u.id) %>"><i class="fa fa-pencil"></i> Editar Admin</a></li>
                                  <li><a href="<%= destroy_clube_manager_path(u.id) %>" data-confirm="Tem certeza que deseja deletar o Adminstrador <%= u.name %>?" data-method="delete" rel="nofollow"><i class="fa fa-trash"></i> Deletar Admin</a></li>
                              </ul>
                          </div>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

   <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>

    <% if flash[:notice] %>
      <script type="text/javascript">
        swal('Okay', '<%= flash[:notice] %>', 'success');
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
        swal('Ops', '<%= flash[:alert] %>', 'warning');
      </script>
    <% end %>

  </body>
</html>

app/views/clubes/create.html.erb
<h1>Clubes#create</h1>
<p>Find me in app/views/clubes/create.html.erb</p>

app/views/clubes/destroy.html.erb
<h1>Clubes#destroy</h1>
<p>Find me in app/views/clubes/destroy.html.erb</p>

app/views/clubes/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'home/sidebar' %>
        
        <%= render 'home/topbar' %>

        <!-- page content -->
        <div class="right_col" role="main">
          
          <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Editar Time</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    
                    <%= render 'form' %>
                  </div>
                </div>
              </div>

            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

   <!-- jQuery -->
    <script src="/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>
  
  </body>
</html>

app/views/clubes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/production/images/favicon.ico" type="image/x-icon"/>
    <title>Torcida Legal</title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render 'home/sidebar' %>
        
        <%= render 'home/topbar' %>

        <!-- page content -->
        <div class="right_col" role="main">
          
          <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Times</h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Nome</th>
                          <th>Thumb</th>
                          <th>Torcidas</th>
                          <th>Status</th>
                          <th style="width:80px">Opções</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @clubes.each do |u| %>
                        <tr>
                          <td><%= u.name %></td>
                          <td><%= image_tag(u.picture.url(:thumb)) %></td>
                          <td><%= u.torcidas.count %></td>
                          <td>
                            <% if u.active > 0 %>
                              <div class="label label-success">Ativo</div>
                            <% else %>
                              <div class="label label-danger">Inativo</div>
                            <% end %>
                          </td>
                          <td>
                              <div class="btn-group">
                              <button type="button" class="btn btn-default">Opções</button>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="<%= edit_clube_path(u.id) %>"><i class="fa fa-pencil"></i> Editar Time</a></li>
                                  <li><a href="<%= clube_path(u.id) %>" data-confirm="Tem certeza que deseja deletar a Time <%= u.name %>? Todas as torcidas ligadas a ele serão deletadas!" data-method="delete" rel="nofollow"><i class="fa fa-trash"></i> Deletar Time</a></li>
                                  <% if u.active > 0 %>
                                    <li><a href="<%= clube_desactive_path(u.id) %>"><i class="fa fa-close"></i> Desativar</a></li>
                                  <% else %>
                                    <li><a href="<%= clube_active_path(u.id) %>"><i class="fa fa-check"></i> Ativar</a></li>
                                  <% end %>
                              </ul>
                          </div>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Torcida Legal
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

   <!-- jQuery -->
    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>
  
    <% if flash[:notice] %>
      <script type="text/javascript">
        swal('Okay', '<%= flash[:notice] %>', 'success');
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
        swal('Ops', '<%= flash[:alert] %>', 'warning');
      </script>
    <% end %>

  </body>
</html>

app/views/clubes/show.html.erb
<h1>Clubes#show</h1>
<p>Find me in app/views/clubes/show.html.erb</p>

app/views/clubes/update.html.erb
<h1>Clubes#update</h1>
<p>Find me in app/views/clubes/update.html.erb</p>